// Generated by scripts/generate_rule_metadata.py from pinned analyzer metadata.
export interface RuleMetadata { description: string; url: string }

export const analyzerRuleMetadata: Record<string, RuleMetadata> = {
  "bandit:B101": {
    "description": "This plugin test checks for the use of the Python assert keyword. It was discovered that some projects used assert to enforce interface constraints. However, assert is removed with compiling to optimised byte code (python -O producing \\*.opt-1.pyc files).",
    "url": "https://bandit.readthedocs.io/en/latest/plugins/b101_assert_used.html"
  },
  "bandit:B102": {
    "description": "This plugin test checks for the use of Python's exec method or keyword. The Python docs succinctly describe why the use of exec is risky.",
    "url": "https://bandit.readthedocs.io/en/latest/plugins/b102_exec_used.html"
  },
  "bandit:B105": {
    "description": "The use of hard-coded passwords increases the possibility of password guessing tremendously. This plugin test looks for all string literals and checks the following conditions:",
    "url": "https://bandit.readthedocs.io/en/latest/plugins/b105_hardcoded_password_string.html"
  },
  "bandit:B108": {
    "description": "Safely creating a temporary file or directory means following a number of rules (see the references for more details). This plugin test looks for strings starting with (configurable) commonly used temporary paths, for example:",
    "url": "https://bandit.readthedocs.io/en/latest/plugins/b108_hardcoded_tmp_directory.html"
  },
  "bandit:B110": {
    "description": "This pattern is considered bad practice in general, but also represents a potential security issue. A larger than normal volume of errors from a service can indicate an attempt is being made to disrupt or interfere with it. Thus errors should, at the very least, be logged.",
    "url": "https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html"
  },
  "bandit:B112": {
    "description": "This pattern is considered bad practice in general, but also represents a potential security issue. A larger than normal volume of errors from a service can indicate an attempt is being made to disrupt or interfere with it. Thus errors should, at the very least, be logged.",
    "url": "https://bandit.readthedocs.io/en/latest/plugins/b112_try_except_continue.html"
  },
  "bandit:B113": {
    "description": "This plugin test checks for requests or httpx calls without a timeout specified.",
    "url": "https://bandit.readthedocs.io/en/latest/plugins/b113_request_without_timeout.html"
  },
  "bandit:B202": {
    "description": "This plugin will look for usage of tarfile.extractall()",
    "url": "https://bandit.readthedocs.io/en/latest/plugins/b202_tarfile_unsafe_members.html"
  },
  "bandit:B301": {
    "description": "Pickle and modules that wrap it can be unsafe when used to deserialize untrusted data, possible security issue.",
    "url": "https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b301-pickle"
  },
  "bandit:B306": {
    "description": "Use of insecure and deprecated function (mktemp).",
    "url": "https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b306-mktemp-q"
  },
  "bandit:B307": {
    "description": "Use of possibly insecure function - consider using safer ast.literal_eval.",
    "url": "https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b307-eval"
  },
  "bandit:B310": {
    "description": "Audit url open for permitted schemes. Allowing use of file:/ or custom schemes is often unexpected.",
    "url": "https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b310-urllib-urlopen"
  },
  "bandit:B311": {
    "description": "Standard pseudo-random generators are not suitable for security/cryptographic purposes.",
    "url": "https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b311-random"
  },
  "bandit:B314": {
    "description": "Using the reported call to parse untrusted XML data is known to be vulnerable to XML attacks. Replace the reported call with its defusedxml equivalent function or make sure defusedxml.defuse_stdlib() is called",
    "url": "https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b313-b319-xml"
  },
  "bandit:B321": {
    "description": "FTP-related functions are being called. FTP is considered insecure. Use SSH/SFTP/SCP or some other encrypted protocol.",
    "url": "https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b321-ftplib"
  },
  "bandit:B324": {
    "description": "This plugin checks for the usage of the insecure MD4, MD5, or SHA1 hash functions in hashlib and crypt. The hashlib.new function provides the ability to construct a new hashing object using the named algorithm. This can be used to create insecure hash functions like MD4 and MD5 if they are passed as algorithm names to this function.",
    "url": "https://bandit.readthedocs.io/en/latest/plugins/b324_hashlib.html"
  },
  "bandit:B402": {
    "description": "A FTP-related module is being imported. FTP is considered insecure. Use SSH/SFTP/SCP or some other encrypted protocol.",
    "url": "https://bandit.readthedocs.io/en/latest/blacklists/blacklist_imports.html#b402-import-ftplib"
  },
  "bandit:B403": {
    "description": "Consider possible security implications associated with the reported module.",
    "url": "https://bandit.readthedocs.io/en/latest/blacklists/blacklist_imports.html#b403-import-pickle"
  },
  "bandit:B404": {
    "description": "Consider possible security implications associated with the subprocess module.",
    "url": "https://bandit.readthedocs.io/en/latest/blacklists/blacklist_imports.html#b404-import-subprocess"
  },
  "bandit:B405": {
    "description": "Using the reported call to parse untrusted XML data is known to be vulnerable to XML attacks. Replace the reported call with the equivalent defusedxml package, or make sure defusedxml.defuse_stdlib() is called.",
    "url": "https://bandit.readthedocs.io/en/latest/blacklists/blacklist_imports.html#b405-import-xml-etree"
  },
  "bandit:B411": {
    "description": "Using the reported call to parse untrusted XML data is known to be vulnerable to XML attacks. Use defusedxml.xmlrpc.monkey_patch() function to monkey-patch xmlrpclib and mitigate XML vulnerabilities.",
    "url": "https://bandit.readthedocs.io/en/latest/blacklists/blacklist_imports.html#b411-import-xmlrpclib"
  },
  "bandit:B506": {
    "description": "This plugin test checks for the unsafe usage of the yaml.load function from the PyYAML package. The yaml.load function provides the ability to construct an arbitrary Python object, which may be dangerous if you receive a YAML document from an untrusted source. The function yaml.safe_load limits this ability to simple Python objects like integers or lists.",
    "url": "https://bandit.readthedocs.io/en/latest/plugins/b506_yaml_load.html"
  },
  "bandit:B602": {
    "description": "This plugin test is part of a family of tests built to check for process spawning and warn appropriately. Specifically, this test looks for the spawning of a subprocess using a command shell. This type of subprocess invocation is dangerous as it is vulnerable to various shell injection attacks.",
    "url": "https://bandit.readthedocs.io/en/latest/plugins/b602_subprocess_popen_with_shell_equals_true.html"
  },
  "bandit:B603": {
    "description": "This plugin test is part of a family of tests built to check for process spawning and warn appropriately. Specifically, this test looks for the spawning of a subprocess without the use of a command shell. This type of subprocess invocation is not vulnerable to shell injection attacks, but care should still be taken to ensure validity of input.",
    "url": "https://bandit.readthedocs.io/en/latest/plugins/b603_subprocess_without_shell_equals_true.html"
  },
  "bandit:B604": {
    "description": "This plugin test is part of a family of tests built to check for process spawning and warn appropriately. Specifically, this plugin test interrogates method calls for the presence of a keyword parameter shell equalling true. It is related to detection of shell injection issues and is intended to catch custom wrappers to vulnerable methods that may have been created.",
    "url": "https://bandit.readthedocs.io/en/latest/plugins/b604_any_other_function_with_shell_equals_true.html"
  },
  "bandit:B605": {
    "description": "This plugin test is part of a family of tests built to check for process spawning and warn appropriately. Specifically, this test looks for the spawning of a subprocess using a command shell. This type of subprocess invocation is dangerous as it is vulnerable to various shell injection attacks.",
    "url": "https://bandit.readthedocs.io/en/latest/plugins/b605_start_process_with_a_shell.html"
  },
  "bandit:B606": {
    "description": "This plugin test is part of a family of tests built to check for process spawning and warn appropriately. Specifically, this test looks for the spawning of a subprocess in a way that doesn't use a shell. Although this is generally safe, it maybe useful for penetration testing workflows to track where external system calls are used.",
    "url": "https://bandit.readthedocs.io/en/latest/plugins/b606_start_process_with_no_shell.html"
  },
  "bandit:B607": {
    "description": "This test will scan the parameters of all configured Python methods, looking for paths that do not start at the filesystem root, that is, do not have a leading '/' character.",
    "url": "https://bandit.readthedocs.io/en/latest/plugins/b607_start_process_with_partial_path.html"
  },
  "bandit:B608": {
    "description": "Unless care is taken to sanitize and control the input data when building such SQL statement strings, an injection attack becomes possible. If strings of this nature are discovered, a LOW confidence issue is reported. In order to boost result confidence, this plugin test will also check to see if the discovered string is in use with standard Python DBAPI calls execute or executemany.",
    "url": "https://bandit.readthedocs.io/en/latest/plugins/b608_hardcoded_sql_expressions.html"
  },
  "bandit:B701": {
    "description": "Unfortunately, autoescaping is False by default. Thus this plugin test will warn on omission of an autoescape setting, as well as an explicit setting of false. A HIGH severity warning is generated in either of these scenarios.",
    "url": "https://bandit.readthedocs.io/en/latest/plugins/b701_jinja2_autoescape_false.html"
  },
  "pylint:abstract-method": {
    "description": "Used when an abstract method (i.e. raise NotImplementedError) is not overridden in concrete class.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/abstract-method.html"
  },
  "pylint:access-member-before-definition": {
    "description": "Used when an instance member is accessed before it's actually assigned.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/error/access-member-before-definition.html"
  },
  "pylint:anomalous-backslash-in-string": {
    "description": "Used when a backslash is in a literal string but not as an escape.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/anomalous-backslash-in-string.html"
  },
  "pylint:arguments-differ": {
    "description": "Used when a method has a different number of arguments than in the implemented interface or in an overridden method. Extra arguments with default values are ignored.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/arguments-differ.html"
  },
  "pylint:arguments-renamed": {
    "description": "Used when a method parameter has a different name than in the implemented interface or in an overridden method.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/arguments-renamed.html"
  },
  "pylint:assignment-from-no-return": {
    "description": "Used when an assignment is done on a function call but the inferred function doesn't return anything.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/error/assignment-from-no-return.html"
  },
  "pylint:assignment-from-none": {
    "description": "Used when an assignment is done on a function call but the inferred function returns nothing but None.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/error/assignment-from-none.html"
  },
  "pylint:attribute-defined-outside-init": {
    "description": "Used when an instance attribute is defined outside the __init__ method.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/attribute-defined-outside-init.html"
  },
  "pylint:bad-classmethod-argument": {
    "description": "Used when a class method has a first argument named differently than the value specified in valid-classmethod-first-arg option (default to \"cls\"), recommended to easily differentiate them from regular instance methods.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/bad-classmethod-argument.html"
  },
  "pylint:bad-exception-cause": {
    "description": "Used when using the syntax \"raise ... from ...\", where the exception cause is not an exception, nor None.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/error/bad-exception-cause.html"
  },
  "pylint:bad-file-encoding": {
    "description": "PEP8 recommends UTF-8 default encoding for Python files. See https://peps.python.org/pep-0008/#source-file-encoding",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/bad-file-encoding.html"
  },
  "pylint:bad-format-string": {
    "description": "Used when a PEP 3101 format string is invalid.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/bad-format-string.html"
  },
  "pylint:bad-indentation": {
    "description": "Used when an unexpected number of indentation's tabulations or spaces has been found.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/bad-indentation.html"
  },
  "pylint:bad-staticmethod-argument": {
    "description": "Used when a static method has \"self\" or a value specified in valid-classmethod-first-arg option or valid-metaclass-classmethod-first-arg option as first argument.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/bad-staticmethod-argument.html"
  },
  "pylint:bad-super-call": {
    "description": "Used when another argument than the current class is given as first argument of the super builtin.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/error/bad-super-call.html"
  },
  "pylint:bare-except": {
    "description": "A bare except: clause will catch SystemExit and KeyboardInterrupt exceptions, making it harder to interrupt a program with Control-C, and can disguise other problems. If you want to catch all exceptions that signal program errors, use except Exception: (bare except is equivalent to except BaseException:).",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/bare-except.html"
  },
  "pylint:broad-exception-caught": {
    "description": "If you use a naked except Exception: clause, you might end up catching exceptions other than the ones you expect to catch. This can hide bugs or make it harder to debug programs when unrelated errors are hidden.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/broad-exception-caught.html"
  },
  "pylint:broad-exception-raised": {
    "description": "Raising exceptions that are too generic force you to catch exceptions generically too. It will force you to use a naked except Exception: clause. You might then end up catching exceptions other than the ones you expect to catch. This can hide bugs or make it harder to debug programs when unrelated errors are hidden.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/broad-exception-raised.html"
  },
  "pylint:cell-var-from-loop": {
    "description": "A variable used in a closure is defined in a loop. This will result in all closures using the same value for the closed-over variable.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/cell-var-from-loop.html"
  },
  "pylint:chained-comparison": {
    "description": "This message is emitted when pylint encounters boolean operation like \"a < b and b < c\", suggesting instead to refactor it to \"a < b < c\"",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/chained-comparison.html"
  },
  "pylint:comparison-with-callable": {
    "description": "This message is emitted when pylint detects that a comparison with a callable was made, which might suggest that some parenthesis were omitted, resulting in potential unwanted behaviour.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/comparison-with-callable.html"
  },
  "pylint:consider-iterating-dictionary": {
    "description": "Emitted when the keys of a dictionary are iterated through the .keys() method or when .keys() is used for a membership check. It is enough to iterate through the dictionary itself, for key in dictionary. For membership checks, if key in dictionary is faster.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/consider-iterating-dictionary.html"
  },
  "pylint:consider-merging-isinstance": {
    "description": "Used when multiple consecutive isinstance calls can be merged into one.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/consider-merging-isinstance.html"
  },
  "pylint:consider-swap-variables": {
    "description": "You do not have to use a temporary variable in order to swap variables. Using \"tuple unpacking\" to directly swap variables makes the intention more clear.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/consider-swap-variables.html"
  },
  "pylint:consider-using-dict-comprehension": {
    "description": "Emitted when we detect the creation of a dictionary using the dict() callable and a transient list. Although there is nothing syntactically wrong with this code, it is hard to read and can be simplified to a dict comprehension. Also it is faster since you don't need to create another transient list",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/consider-using-dict-comprehension.html"
  },
  "pylint:consider-using-dict-items": {
    "description": "Emitted when iterating over the keys of a dictionary and accessing the value by index lookup. Both the key and value can be accessed by iterating using the .items() method of the dictionary instead.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/consider-using-dict-items.html"
  },
  "pylint:consider-using-enumerate": {
    "description": "Emitted when code that iterates with range and len is encountered. Such code can be simplified by using the enumerate builtin.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/consider-using-enumerate.html"
  },
  "pylint:consider-using-f-string": {
    "description": "Used when we detect a string that is being formatted with format() or % which could potentially be an f-string. The use of f-strings is preferred. Requires Python 3.6 and py-version >= 3.6.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/consider-using-f-string.html"
  },
  "pylint:consider-using-from-import": {
    "description": "Emitted when a submodule of a package is imported and aliased with the same name, e.g., instead of import concurrent.futures as futures use from concurrent import futures.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/consider-using-from-import.html"
  },
  "pylint:consider-using-generator": {
    "description": "If your container can be large using a generator will bring better performance.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/consider-using-generator.html"
  },
  "pylint:consider-using-get": {
    "description": "Using the builtin dict.get for getting a value from a dictionary if a key is present or a default if not, is simpler and considered more idiomatic, although sometimes a bit slower",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/consider-using-get.html"
  },
  "pylint:consider-using-in": {
    "description": "To check if a variable is equal to one of many values, combine the values into a set or tuple and check if the variable is contained \"in\" it instead of checking for equality against each of the values. This is faster and less verbose.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/consider-using-in.html"
  },
  "pylint:consider-using-join": {
    "description": "Using str.join(sequence) is faster, uses less memory and increases readability compared to for-loop iteration.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/consider-using-join.html"
  },
  "pylint:consider-using-max-builtin": {
    "description": "Using the max builtin instead of a conditional improves readability and conciseness.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/consider-using-max-builtin.html"
  },
  "pylint:consider-using-min-builtin": {
    "description": "Using the min builtin instead of a conditional improves readability and conciseness.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/consider-using-min-builtin.html"
  },
  "pylint:consider-using-set-comprehension": {
    "description": "Although there is nothing syntactically wrong with this code, it is hard to read and can be simplified to a set comprehension. Also it is faster since you don't need to create another transient list",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/consider-using-set-comprehension.html"
  },
  "pylint:consider-using-sys-exit": {
    "description": "Contrary to 'exit()' or 'quit()', 'sys.exit' does not rely on the site module being available (as the 'sys' module is always available).",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/consider-using-sys-exit.html"
  },
  "pylint:consider-using-ternary": {
    "description": "Used when one of known pre-python 2.5 ternary syntax is used.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/consider-using-ternary.html"
  },
  "pylint:consider-using-with": {
    "description": "Emitted if a resource-allocating assignment or call may be replaced by a 'with' block. By using 'with' the release of the allocated resources is ensured even in the case of an exception.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/consider-using-with.html"
  },
  "pylint:cyclic-import": {
    "description": "Used when a cyclic import between two or more modules is detected.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/cyclic-import.html"
  },
  "pylint:dangerous-default-value": {
    "description": "Used when a mutable value as list or dictionary is detected in a default value for an argument.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/dangerous-default-value.html"
  },
  "pylint:deprecated-argument": {
    "description": "The argument is marked as deprecated and will be removed in the future.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/deprecated-argument.html"
  },
  "pylint:deprecated-class": {
    "description": "The class is marked as deprecated and will be removed in the future.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/deprecated-class.html"
  },
  "pylint:deprecated-method": {
    "description": "The method is marked as deprecated and will be removed in the future.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/deprecated-method.html"
  },
  "pylint:deprecated-module": {
    "description": "A module marked as deprecated is imported.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/deprecated-module.html"
  },
  "pylint:disallowed-name": {
    "description": "Used when the name matches bad-names or bad-names-rgxs- (unauthorized names).",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/disallowed-name.html"
  },
  "pylint:duplicate-code": {
    "description": "Indicates that a set of similar lines has been detected among multiple file. This usually means that the code should be refactored to avoid this duplication.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/duplicate-code.html"
  },
  "pylint:duplicate-except": {
    "description": "Used when an except catches a type that was already caught by a previous handler.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/duplicate-except.html"
  },
  "pylint:duplicate-key": {
    "description": "Used when a dictionary expression binds the same key multiple times.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/duplicate-key.html"
  },
  "pylint:duplicate-string-formatting-argument": {
    "description": "Used when we detect that a string formatting is repeating an argument instead of using named string arguments",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/duplicate-string-formatting-argument.html"
  },
  "pylint:empty-docstring": {
    "description": "Used when a module, function, class or method has an empty docstring (it would be too easy ;).",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/empty-docstring.html"
  },
  "pylint:eval-used": {
    "description": "Used when you use the \"eval\" function, to discourage its usage. Consider using ast.literal_eval for safely evaluating strings containing Python expressions from untrusted sources.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/eval-used.html"
  },
  "pylint:exec-used": {
    "description": "Raised when the 'exec' statement is used. It's dangerous to use this function for a user input, and it's also slower than actual code in general. This doesn't mean you should never use it, but you should consider alternatives first and restrict the functions available.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/exec-used.html"
  },
  "pylint:expression-not-assigned": {
    "description": "Used when an expression that is not a function call is assigned to nothing. Probably something else was intended.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/expression-not-assigned.html"
  },
  "pylint:f-string-without-interpolation": {
    "description": "Used when we detect an f-string that does not use any interpolation variables, in which case it can be either a normal string or a bug in the code.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/f-string-without-interpolation.html"
  },
  "pylint:fatal": {
    "description": "Used when an error occurred preventing the analysis of a module (unable to find it for instance).",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/fatal/fatal.html"
  },
  "pylint:fixme": {
    "description": "Used when a warning note as FIXME or XXX is detected.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/fixme.html"
  },
  "pylint:format-string-without-interpolation": {
    "description": "Used when we detect a string that does not have any interpolation variables, in which case it can be either a normal string without formatting or a bug in the code.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/format-string-without-interpolation.html"
  },
  "pylint:function-redefined": {
    "description": "Used when a function / class / method is redefined.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/error/function-redefined.html"
  },
  "pylint:global-statement": {
    "description": "Used when you use the \"global\" statement to update a global variable. Pylint discourages its usage. That doesn't mean you cannot use it!",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/global-statement.html"
  },
  "pylint:global-variable-not-assigned": {
    "description": "When a variable defined in the global scope is modified in an inner scope, the 'global' keyword is required in the inner scope only if there is an assignment operation done in the inner scope.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/global-variable-not-assigned.html"
  },
  "pylint:global-variable-undefined": {
    "description": "Used when a variable is defined through the \"global\" statement but the variable is not defined in the module scope.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/global-variable-undefined.html"
  },
  "pylint:implicit-str-concat": {
    "description": "String literals are implicitly concatenated in a literal iterable definition : maybe a comma is missing ?",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/implicit-str-concat.html"
  },
  "pylint:import-outside-toplevel": {
    "description": "Used when an import statement is used anywhere other than the module toplevel. Move this import to the top of the file.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/import-outside-toplevel.html"
  },
  "pylint:import-self": {
    "description": "Used when a module is importing itself.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/import-self.html"
  },
  "pylint:inconsistent-return-statements": {
    "description": "According to PEP8, if any return statement returns an expression, any return statements where no value is returned should explicitly state this as return None, and an explicit return statement should be present at the end of the function (if reachable)",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/inconsistent-return-statements.html"
  },
  "pylint:invalid-index-returned": {
    "description": "Used when an __index__ method returns something which is not an integer",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/error/invalid-index-returned.html"
  },
  "pylint:invalid-name": {
    "description": "Used when the name doesn't conform to naming rules associated to its type (constant, variable, class...).",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/invalid-name.html"
  },
  "pylint:invalid-repr-returned": {
    "description": "Used when a __repr__ method returns something which is not a string",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/error/invalid-repr-returned.html"
  },
  "pylint:invalid-str-returned": {
    "description": "Used when a __str__ method returns something which is not a string",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/error/invalid-str-returned.html"
  },
  "pylint:keyword-arg-before-vararg": {
    "description": "When defining a keyword argument before variable positional arguments, one can end up in having multiple values passed for the aforementioned parameter in case the method is called with keyword arguments.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/keyword-arg-before-vararg.html"
  },
  "pylint:line-too-long": {
    "description": "Used when a line is longer than a given number of characters.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/line-too-long.html"
  },
  "pylint:logging-format-interpolation": {
    "description": "Used when a logging statement has a call form of \"logging.<logging method>(format_string.format(format_args...))\". Use another type of string formatting instead. You can use % formatting but leave interpolation to the logging function by passing the parameters as arguments. If logging-fstring-interpolation is disabled then you can use fstring formatting. If logging-not-lazy is disabled then you can use % formatting as normal.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/logging-format-interpolation.html"
  },
  "pylint:logging-fstring-interpolation": {
    "description": "Used when a logging statement has a call form of \"logging.<logging method>(f\"...\")\".Use another type of string formatting instead. You can use % formatting but leave interpolation to the logging function by passing the parameters as arguments. If logging-format-interpolation is disabled then you can use str.format. If logging-not-lazy is disabled then you can use % formatting as normal.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/logging-fstring-interpolation.html"
  },
  "pylint:logging-not-lazy": {
    "description": "Used when a logging statement has a call form of \"logging.<logging method>(format_string % (format_args...))\". Use another type of string formatting instead. You can use % formatting but leave interpolation to the logging function by passing the parameters as arguments. If logging-fstring-interpolation is disabled then you can use fstring formatting. If logging-format-interpolation is disabled then you can use str.format.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/logging-not-lazy.html"
  },
  "pylint:logging-too-few-args": {
    "description": "Used when a logging format string is given too few arguments.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/error/logging-too-few-args.html"
  },
  "pylint:method-hidden": {
    "description": "Used when a class defines a method which is hidden by an instance attribute from an ancestor class or set by some client code.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/error/method-hidden.html"
  },
  "pylint:misplaced-bare-raise": {
    "description": "Used when a bare raise is not used inside an except clause. This generates an error, since there are no active exceptions to be reraised. An exception to this rule is represented by a bare raise inside a finally clause, which might work, as long as an exception is raised inside the try block, but it is nevertheless a code smell that must not be relied upon.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/error/misplaced-bare-raise.html"
  },
  "pylint:missing-class-docstring": {
    "description": "Used when a class has no docstring. Even an empty class must have a docstring.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/missing-class-docstring.html"
  },
  "pylint:missing-final-newline": {
    "description": "Used when the last line in a file is missing a newline.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/missing-final-newline.html"
  },
  "pylint:missing-format-argument-key": {
    "description": "Used when a PEP 3101 format string that uses named fields doesn't receive one or more required keywords.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/missing-format-argument-key.html"
  },
  "pylint:missing-function-docstring": {
    "description": "Used when a function or method has no docstring. Some special methods like __init__ do not require a docstring.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/missing-function-docstring.html"
  },
  "pylint:missing-module-docstring": {
    "description": "Used when a module has no docstring. Empty modules do not require a docstring.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/missing-module-docstring.html"
  },
  "pylint:modified-iterating-dict": {
    "description": "Emitted when items are added or removed to a dict being iterated through. Doing so raises a RuntimeError.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/error/modified-iterating-dict.html"
  },
  "pylint:modified-iterating-list": {
    "description": "Emitted when items are added or removed to a list being iterated through. Doing so can result in unexpected behaviour, that is why it is preferred to use a copy of the list.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/modified-iterating-list.html"
  },
  "pylint:multiple-imports": {
    "description": "Used when import statement importing multiple modules is detected.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/multiple-imports.html"
  },
  "pylint:multiple-statements": {
    "description": "Used when more than on statement are found on the same line.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/multiple-statements.html"
  },
  "pylint:no-classmethod-decorator": {
    "description": "Used when a class method is defined without using the decorator syntax.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/no-classmethod-decorator.html"
  },
  "pylint:no-else-break": {
    "description": "Used in order to highlight an unnecessary block of code following an if containing a break statement. As such, it will warn when it encounters an else following a chain of ifs, all of them containing a break statement.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/no-else-break.html"
  },
  "pylint:no-else-continue": {
    "description": "Used in order to highlight an unnecessary block of code following an if containing a continue statement. As such, it will warn when it encounters an else following a chain of ifs, all of them containing a continue statement.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/no-else-continue.html"
  },
  "pylint:no-else-raise": {
    "description": "Used in order to highlight an unnecessary block of code following an if, or a try/except containing a raise statement. As such, it will warn when it encounters an else following a chain of ifs, all of them containing a raise statement.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/no-else-raise.html"
  },
  "pylint:no-else-return": {
    "description": "Used in order to highlight an unnecessary block of code following an if, or a try/except containing a return statement. As such, it will warn when it encounters an else following a chain of ifs, all of them containing a return statement.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/no-else-return.html"
  },
  "pylint:no-member": {
    "description": "Used when a variable is accessed for a nonexistent member.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/error/no-member.html"
  },
  "pylint:no-method-argument": {
    "description": "Used when a method which should have the bound instance as first argument has no argument defined.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/error/no-method-argument.html"
  },
  "pylint:no-self-argument": {
    "description": "Used when a method has an attribute different the \"self\" as first argument. This is considered as an error since this is a so common convention that you shouldn't break it!",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/error/no-self-argument.html"
  },
  "pylint:no-staticmethod-decorator": {
    "description": "Used when a static method is defined without using the decorator syntax.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/no-staticmethod-decorator.html"
  },
  "pylint:no-value-for-parameter": {
    "description": "Used when a function call passes too few arguments.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/error/no-value-for-parameter.html"
  },
  "pylint:non-iterator-returned": {
    "description": "Used when an __iter__ method returns something which is not an iterable (i.e. has no __next__ method)",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/error/non-iterator-returned.html"
  },
  "pylint:non-parent-init-called": {
    "description": "Used when an __init__ method is called on a class which is not in the direct ancestors for the analysed class.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/non-parent-init-called.html"
  },
  "pylint:not-callable": {
    "description": "Used when an object being called has been inferred to a non callable object.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/error/not-callable.html"
  },
  "pylint:notimplemented-raised": {
    "description": "Used when NotImplemented is raised instead of NotImplementedError",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/error/notimplemented-raised.html"
  },
  "pylint:pointless-exception-statement": {
    "description": "Used when an exception is created without being assigned, raised or returned for subsequent use elsewhere.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/pointless-exception-statement.html"
  },
  "pylint:pointless-statement": {
    "description": "Used when a statement doesn't have (or at least seems to) any effect.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/pointless-statement.html"
  },
  "pylint:pointless-string-statement": {
    "description": "Used when a string is used as a statement (which of course has no effect). This is a particular case of W0104 with its own message so you can easily disable it if you're using those strings as documentation, instead of comments.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/pointless-string-statement.html"
  },
  "pylint:possibly-unused-variable": {
    "description": "Used when a variable is defined but might not be used. The possibility comes from the fact that locals() might be used, which could consume or not the said variable",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/possibly-unused-variable.html"
  },
  "pylint:possibly-used-before-assignment": {
    "description": "Emitted when a local variable is accessed before its assignment took place in both branches of an if/else switch.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/error/possibly-used-before-assignment.html"
  },
  "pylint:protected-access": {
    "description": "Used when a protected member (i.e. class member with a name beginning with an underscore) is accessed outside the class or a descendant of the class where it's defined.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/protected-access.html"
  },
  "pylint:raise-missing-from": {
    "description": "Python's exception chaining shows the traceback of the current exception, but also of the original exception. When you raise a new exception after another exception was caught it's likely that the second exception is a friendly re-wrapping of the first exception. In such cases raise from provides a better link between the two tracebacks in the final error.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/raise-missing-from.html"
  },
  "pylint:raising-bad-type": {
    "description": "Used when something which is neither a class nor an instance is raised (i.e. a TypeError will be raised).",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/error/raising-bad-type.html"
  },
  "pylint:raising-format-tuple": {
    "description": "Used when passing multiple arguments to an exception constructor, the first of them a string literal containing what appears to be placeholders intended for formatting",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/raising-format-tuple.html"
  },
  "pylint:redefined-argument-from-local": {
    "description": "Used when a local name is redefining an argument, which might suggest a potential error. This is taken in account only for a handful of name binding operations, such as for iteration, with statement assignment and exception handler assignment.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/redefined-argument-from-local.html"
  },
  "pylint:redefined-builtin": {
    "description": "Used when a variable or function override a built-in.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/redefined-builtin.html"
  },
  "pylint:redefined-outer-name": {
    "description": "Used when a variable's name hides a name defined in an outer scope or except handler.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/redefined-outer-name.html"
  },
  "pylint:redundant-keyword-arg": {
    "description": "Used when a function call would result in assigning multiple values to a function parameter, one value from a positional argument and one from a keyword argument.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/error/redundant-keyword-arg.html"
  },
  "pylint:redundant-u-string-prefix": {
    "description": "Used when we detect a string with a u prefix. These prefixes were necessary in Python 2 to indicate a string was Unicode, but since Python 3.0 strings are Unicode by default.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/redundant-u-string-prefix.html"
  },
  "pylint:reimported": {
    "description": "Used when a module is imported more than once.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/reimported.html"
  },
  "pylint:self-assigning-variable": {
    "description": "Emitted when we detect that a variable is assigned to itself",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/self-assigning-variable.html"
  },
  "pylint:self-cls-assignment": {
    "description": "Invalid assignment to self or cls in instance or class method respectively.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/self-cls-assignment.html"
  },
  "pylint:signature-differs": {
    "description": "Used when a method signature is different than in the implemented interface or in an overridden method.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/signature-differs.html"
  },
  "pylint:simplifiable-condition": {
    "description": "Emitted when a boolean condition is able to be simplified.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/simplifiable-condition.html"
  },
  "pylint:simplifiable-if-expression": {
    "description": "Used when an if expression can be replaced with 'bool(test)' or simply 'test' if the boolean cast is implicit.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/simplifiable-if-expression.html"
  },
  "pylint:simplifiable-if-statement": {
    "description": "Used when an if statement can be replaced with 'bool(test)'.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/simplifiable-if-statement.html"
  },
  "pylint:singleton-comparison": {
    "description": "Used when an expression is compared to singleton values like True, False or None.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/singleton-comparison.html"
  },
  "pylint:stop-iteration-return": {
    "description": "According to PEP479, the raise of StopIteration to end the loop of a generator may lead to hard to find bugs. This PEP specify that raise StopIteration has to be replaced by a simple return statement",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/stop-iteration-return.html"
  },
  "pylint:subprocess-run-check": {
    "description": "The check keyword is set to False by default. It means the process launched by subprocess.run can exit with a non-zero exit code and fail silently. It's better to set it explicitly to make clear what the error-handling behavior is.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/subprocess-run-check.html"
  },
  "pylint:super-init-not-called": {
    "description": "Used when an ancestor class method has an __init__ method which is not called by a derived class.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/super-init-not-called.html"
  },
  "pylint:super-with-arguments": {
    "description": "Emitted when calling the super() builtin with the current class and instance. On Python 3 these arguments are the default and they can be omitted.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/super-with-arguments.html"
  },
  "pylint:superfluous-parens": {
    "description": "Used when a single item in parentheses follows an if, for, or other keyword.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/superfluous-parens.html"
  },
  "pylint:syntax-error": {
    "description": "Used when a syntax error is raised for a module.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/error/syntax-error.html"
  },
  "pylint:too-few-format-args": {
    "description": "Used when a format string that uses unnamed conversion specifiers is given too few arguments",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/error/too-few-format-args.html"
  },
  "pylint:too-few-public-methods": {
    "description": "Used when class has too few public methods, so be sure it's really worth it.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/too-few-public-methods.html"
  },
  "pylint:too-many-ancestors": {
    "description": "Used when class has too many parent classes, try to reduce this to get a simpler (and so easier to use) class.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/too-many-ancestors.html"
  },
  "pylint:too-many-arguments": {
    "description": "Used when a function or method takes too many arguments.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/too-many-arguments.html"
  },
  "pylint:too-many-boolean-expressions": {
    "description": "Used when an if statement contains too many boolean expressions.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/too-many-boolean-expressions.html"
  },
  "pylint:too-many-branches": {
    "description": "Used when a function or method has too many branches, making it hard to follow.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/too-many-branches.html"
  },
  "pylint:too-many-format-args": {
    "description": "Used when a format string that uses unnamed conversion specifiers is given too many arguments.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/error/too-many-format-args.html"
  },
  "pylint:too-many-function-args": {
    "description": "Used when a function call passes too many positional arguments.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/error/too-many-function-args.html"
  },
  "pylint:too-many-instance-attributes": {
    "description": "Used when class has too many instance attributes, try to reduce this to get a simpler (and so easier to use) class.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/too-many-instance-attributes.html"
  },
  "pylint:too-many-lines": {
    "description": "Used when a module has too many lines, reducing its readability.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/too-many-lines.html"
  },
  "pylint:too-many-locals": {
    "description": "Used when a function or method has too many local variables.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/too-many-locals.html"
  },
  "pylint:too-many-nested-blocks": {
    "description": "Used when a function or a method has too many nested blocks. This makes the code less understandable and maintainable.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/too-many-nested-blocks.html"
  },
  "pylint:too-many-positional-arguments": {
    "description": "Used when a function has too many positional arguments.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/too-many-positional-arguments.html"
  },
  "pylint:too-many-public-methods": {
    "description": "Used when class has too many public methods, try to reduce this to get a simpler (and so easier to use) class.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/too-many-public-methods.html"
  },
  "pylint:too-many-return-statements": {
    "description": "Used when a function or method has too many return statement, making it hard to follow.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/too-many-return-statements.html"
  },
  "pylint:too-many-statements": {
    "description": "Used when a function or method has too many statements. You should then split it in smaller functions / methods.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/too-many-statements.html"
  },
  "pylint:trailing-comma-tuple": {
    "description": "In Python, a tuple is actually created by the comma symbol, not by the parentheses. Unfortunately, one can actually create a tuple by misplacing a trailing comma, which can lead to potential weird bugs in your code. You should always use parentheses explicitly for creating a tuple.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/trailing-comma-tuple.html"
  },
  "pylint:trailing-newlines": {
    "description": "Used when there are trailing blank lines in a file.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/trailing-newlines.html"
  },
  "pylint:trailing-whitespace": {
    "description": "Used when there is whitespace between the end of a line and the newline.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/trailing-whitespace.html"
  },
  "pylint:try-except-raise": {
    "description": "Used when an except handler uses raise as its first or only operator. This is useless because it raises back the exception immediately. Remove the raise operator or the entire try-except-raise block!",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/try-except-raise.html"
  },
  "pylint:unbalanced-tuple-unpacking": {
    "description": "Used when there is an unbalanced tuple unpacking in assignment",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/unbalanced-tuple-unpacking.html"
  },
  "pylint:undefined-loop-variable": {
    "description": "Used when a loop variable (i.e. defined by a for loop or a list comprehension or a generator expression) is used outside the loop.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/undefined-loop-variable.html"
  },
  "pylint:undefined-variable": {
    "description": "Used when an undefined variable is accessed.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/error/undefined-variable.html"
  },
  "pylint:unexpected-keyword-arg": {
    "description": "Used when a function call passes a keyword argument that doesn't correspond to one of the function's parameter names.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/error/unexpected-keyword-arg.html"
  },
  "pylint:ungrouped-imports": {
    "description": "Used when imports are not grouped by packages.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/ungrouped-imports.html"
  },
  "pylint:unidiomatic-typecheck": {
    "description": "The idiomatic way to perform an explicit typecheck in Python is to use isinstance(x, Y) rather than type(x) == Y, type(x) is Y. Though there are unusual situations where these give different results.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/unidiomatic-typecheck.html"
  },
  "pylint:unnecessary-comprehension": {
    "description": "Instead of using an identity comprehension, consider using the list, dict or set constructor. It is faster and simpler.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/unnecessary-comprehension.html"
  },
  "pylint:unnecessary-dict-index-lookup": {
    "description": "Emitted when iterating over the dictionary items (key-item pairs) and accessing the value by index lookup. The value can be accessed directly instead.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/unnecessary-dict-index-lookup.html"
  },
  "pylint:unnecessary-dunder-call": {
    "description": "Used when a dunder method is manually called instead of using the corresponding function/method/operator.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/unnecessary-dunder-call.html"
  },
  "pylint:unnecessary-ellipsis": {
    "description": "Used when the ellipsis constant is encountered and can be avoided. A line of code consisting of an ellipsis is unnecessary if there is a docstring on the preceding line or if there is a statement in the same scope.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/unnecessary-ellipsis.html"
  },
  "pylint:unnecessary-lambda": {
    "description": "Used when the body of a lambda expression is a function call on the same argument list as the lambda itself; such lambda expressions are in all but a few cases replaceable with the function being called in the body of the lambda.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/unnecessary-lambda.html"
  },
  "pylint:unnecessary-lambda-assignment": {
    "description": "Used when a lambda expression is assigned to variable rather than defining a standard function with the \"def\" keyword.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/unnecessary-lambda-assignment.html"
  },
  "pylint:unnecessary-list-index-lookup": {
    "description": "Emitted when iterating over an enumeration and accessing the value by index lookup. The value can be accessed directly instead.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/unnecessary-list-index-lookup.html"
  },
  "pylint:unnecessary-negation": {
    "description": "Used when a boolean expression contains an unneeded negation, e.g. when two negation operators cancel each other out.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/unnecessary-negation.html"
  },
  "pylint:unnecessary-pass": {
    "description": "Used when a \"pass\" statement can be removed without affecting the behaviour of the code.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/unnecessary-pass.html"
  },
  "pylint:unnecessary-semicolon": {
    "description": "Used when a statement is ended by a semi-colon (\";\"), which isn't necessary (that's python, not C ;).",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/unnecessary-semicolon.html"
  },
  "pylint:unpacking-non-sequence": {
    "description": "Used when something which is not a sequence is used in an unpack assignment",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/error/unpacking-non-sequence.html"
  },
  "pylint:unreachable": {
    "description": "Used when there is some code behind a \"return\" or \"raise\" statement, which will never be accessed.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/unreachable.html"
  },
  "pylint:unspecified-encoding": {
    "description": "It is better to specify an encoding when opening documents. Using the system default implicitly can create problems on other operating systems. See https://peps.python.org/pep-0597/",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/unspecified-encoding.html"
  },
  "pylint:unsubscriptable-object": {
    "description": "Emitted when a subscripted value doesn't support subscription (i.e. doesn't define __getitem__ method or __class_getitem__ for a class).",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/error/unsubscriptable-object.html"
  },
  "pylint:unsupported-assignment-operation": {
    "description": "Emitted when an object does not support item assignment (i.e. doesn't define __setitem__ method).",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/error/unsupported-assignment-operation.html"
  },
  "pylint:unused-argument": {
    "description": "Used when a function or method argument is not used.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/unused-argument.html"
  },
  "pylint:unused-format-string-argument": {
    "description": "Used when a PEP 3101 format string that uses named fields is used with an argument that is not required by the format string.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/unused-format-string-argument.html"
  },
  "pylint:unused-import": {
    "description": "Used when an imported module or variable is not used.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/unused-import.html"
  },
  "pylint:unused-private-member": {
    "description": "Emitted when a private member of a class is defined but not used.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/unused-private-member.html"
  },
  "pylint:unused-variable": {
    "description": "Used when a variable is defined but not used.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/unused-variable.html"
  },
  "pylint:unused-wildcard-import": {
    "description": "Used when an imported module or variable is not used from a 'from X import *' style import.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/unused-wildcard-import.html"
  },
  "pylint:use-a-generator": {
    "description": "Comprehension inside of 'any', 'all', 'max', 'min' or 'sum' is unnecessary. A generator would be sufficient and faster.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/use-a-generator.html"
  },
  "pylint:use-dict-literal": {
    "description": "Emitted when using dict() to create a dictionary instead of a literal '{ ... }'. The literal is faster as it avoids an additional function call.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/use-dict-literal.html"
  },
  "pylint:use-implicit-booleaness-not-comparison": {
    "description": "Empty sequences are considered false in a boolean context. Following this check blindly in weakly typed code base can create hard to debug issues. If the value can be something else that is falsey but not a sequence (for example None, an empty string, or 0) the code will not be equivalent.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/use-implicit-booleaness-not-comparison.html"
  },
  "pylint:use-implicit-booleaness-not-len": {
    "description": "Empty sequences are considered false in a boolean context. You can either remove the call to 'len' (if not x) or compare the length against a scalar (if len(x) > 1).",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/use-implicit-booleaness-not-len.html"
  },
  "pylint:use-list-literal": {
    "description": "Emitted when using list() to create an empty list instead of the literal []. The literal is faster as it avoids an additional function call.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/use-list-literal.html"
  },
  "pylint:use-maxsplit-arg": {
    "description": "Emitted when accessing only the first or last element of str.split(). The first and last element can be accessed by using str.split(sep, maxsplit=1)[0] or str.rsplit(sep, maxsplit=1)[-1] instead.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/use-maxsplit-arg.html"
  },
  "pylint:use-sequence-for-iteration": {
    "description": "When iterating over values, sequence types (e.g., lists, tuples, ranges) are more efficient than sets.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/use-sequence-for-iteration.html"
  },
  "pylint:use-yield-from": {
    "description": "Yielding directly from the iterator is faster and arguably cleaner code than yielding each element one by one in the loop.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/use-yield-from.html"
  },
  "pylint:used-before-assignment": {
    "description": "Emitted when a local variable is accessed before its assignment took place. Assignments in try blocks are assumed not to have occurred when evaluating associated except/finally blocks. Assignments in except blocks are assumed not to have occurred when evaluating statements outside the block, except when the associated try block contains a return statement.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/error/used-before-assignment.html"
  },
  "pylint:useless-else-on-loop": {
    "description": "Loops should only have an else clause if they can exit early with a break statement, otherwise the statements under else should be on the same scope as the loop itself.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/useless-else-on-loop.html"
  },
  "pylint:useless-object-inheritance": {
    "description": "Used when a class inherit from object, which under python3 is implicit, hence can be safely removed from bases.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/useless-object-inheritance.html"
  },
  "pylint:useless-parent-delegation": {
    "description": "Used whenever we can detect that an overridden method is useless, relying on parent or super() delegation to do the same thing as another method from the MRO.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/useless-parent-delegation.html"
  },
  "pylint:useless-return": {
    "description": "Emitted when a single \"return\" or \"return None\" statement is found at the end of function or method definition. This statement can safely be removed because Python will implicitly return None",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/useless-return.html"
  },
  "pylint:using-constant-test": {
    "description": "Emitted when a conditional statement (If or ternary if) uses a constant value for its test. This might not be what the user intended to do.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/using-constant-test.html"
  },
  "pylint:wildcard-import": {
    "description": "Used when from module import * is detected.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/wildcard-import.html"
  },
  "pylint:wrong-import-order": {
    "description": "Used when PEP8 import order is not respected (standard imports first, then third-party libraries, then local imports).",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/wrong-import-order.html"
  },
  "pylint:wrong-import-position": {
    "description": "Used when code and imports are mixed.",
    "url": "https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/wrong-import-position.html"
  },
  "ruff:B004": {
    "description": "Checks for uses of hasattr to test if an object is callable (e.g., hasattr(obj, \"__call__\")).",
    "url": "https://docs.astral.sh/ruff/rules/unreliable-callable-check/"
  },
  "ruff:B005": {
    "description": "Checks for uses of multi-character strings in .strip(), .lstrip(), and .rstrip() calls.",
    "url": "https://docs.astral.sh/ruff/rules/strip-with-multi-characters/"
  },
  "ruff:B006": {
    "description": "Checks for uses of mutable objects as function argument defaults.",
    "url": "https://docs.astral.sh/ruff/rules/mutable-argument-default/"
  },
  "ruff:B007": {
    "description": "Checks for unused variables in loops (e.g., for and while statements).",
    "url": "https://docs.astral.sh/ruff/rules/unused-loop-control-variable/"
  },
  "ruff:B008": {
    "description": "Checks for function calls in default function arguments.",
    "url": "https://docs.astral.sh/ruff/rules/function-call-in-default-argument/"
  },
  "ruff:B009": {
    "description": "Checks for uses of getattr that take a constant attribute value as an argument (e.g., getattr(obj, \"foo\")).",
    "url": "https://docs.astral.sh/ruff/rules/get-attr-with-constant/"
  },
  "ruff:B010": {
    "description": "Checks for uses of setattr that take a constant attribute value as an argument (e.g., setattr(obj, \"foo\", 42)).",
    "url": "https://docs.astral.sh/ruff/rules/set-attr-with-constant/"
  },
  "ruff:B011": {
    "description": "Checks for uses of assert False.",
    "url": "https://docs.astral.sh/ruff/rules/assert-false/"
  },
  "ruff:B013": {
    "description": "Checks for single-element tuples in exception handlers (e.g., except (ValueError,):).",
    "url": "https://docs.astral.sh/ruff/rules/redundant-tuple-in-exception-handler/"
  },
  "ruff:B015": {
    "description": "Checks for useless comparisons.",
    "url": "https://docs.astral.sh/ruff/rules/useless-comparison/"
  },
  "ruff:B016": {
    "description": "Checks for raise statements that raise a literal value.",
    "url": "https://docs.astral.sh/ruff/rules/raise-literal/"
  },
  "ruff:B018": {
    "description": "Checks for useless expressions.",
    "url": "https://docs.astral.sh/ruff/rules/useless-expression/"
  },
  "ruff:B019": {
    "description": "Checks for uses of the functools.lru_cache and functools.cache decorators on methods.",
    "url": "https://docs.astral.sh/ruff/rules/cached-instance-method/"
  },
  "ruff:B020": {
    "description": "Checks for loop control variables that override the loop iterable.",
    "url": "https://docs.astral.sh/ruff/rules/loop-variable-overrides-iterator/"
  },
  "ruff:B023": {
    "description": "Checks for function definitions that use a loop variable.",
    "url": "https://docs.astral.sh/ruff/rules/function-uses-loop-variable/"
  },
  "ruff:B024": {
    "description": "Checks for abstract classes without abstract methods or properties. Annotated but unassigned class variables are regarded as abstract.",
    "url": "https://docs.astral.sh/ruff/rules/abstract-base-class-without-abstract-method/"
  },
  "ruff:B026": {
    "description": "Checks for function calls that use star-argument unpacking after providing a keyword argument",
    "url": "https://docs.astral.sh/ruff/rules/star-arg-unpacking-after-keyword-arg/"
  },
  "ruff:B027": {
    "description": "Checks for empty methods in abstract base classes without an abstract decorator.",
    "url": "https://docs.astral.sh/ruff/rules/empty-method-without-abstract-decorator/"
  },
  "ruff:B028": {
    "description": "Checks for warnings.warn calls without an explicit stacklevel keyword argument.",
    "url": "https://docs.astral.sh/ruff/rules/no-explicit-stacklevel/"
  },
  "ruff:B904": {
    "description": "Checks for raise statements in exception handlers that lack a from clause.",
    "url": "https://docs.astral.sh/ruff/rules/raise-without-from-inside-except/"
  },
  "ruff:B905": {
    "description": "Checks for zip calls without an explicit strict parameter when called with two or more iterables, or any starred argument.",
    "url": "https://docs.astral.sh/ruff/rules/zip-without-explicit-strict/"
  },
  "ruff:C901": {
    "description": "Checks for functions with a high McCabe complexity.",
    "url": "https://docs.astral.sh/ruff/rules/complex-structure/"
  },
  "ruff:E101": {
    "description": "Checks for mixed tabs and spaces in indentation.",
    "url": "https://docs.astral.sh/ruff/rules/mixed-spaces-and-tabs/"
  },
  "ruff:E401": {
    "description": "Check for multiple imports on one line.",
    "url": "https://docs.astral.sh/ruff/rules/multiple-imports-on-one-line/"
  },
  "ruff:E402": {
    "description": "Checks for imports that are not at the top of the file.",
    "url": "https://docs.astral.sh/ruff/rules/module-import-not-at-top-of-file/"
  },
  "ruff:E501": {
    "description": "Checks for lines that exceed the specified maximum character length.",
    "url": "https://docs.astral.sh/ruff/rules/line-too-long/"
  },
  "ruff:E701": {
    "description": "Checks for compound statements (multiple statements on the same line).",
    "url": "https://docs.astral.sh/ruff/rules/multiple-statements-on-one-line-colon/"
  },
  "ruff:E703": {
    "description": "Checks for statements that end with an unnecessary semicolon.",
    "url": "https://docs.astral.sh/ruff/rules/useless-semicolon/"
  },
  "ruff:E711": {
    "description": "Checks for comparisons to None which are not using the is operator.",
    "url": "https://docs.astral.sh/ruff/rules/none-comparison/"
  },
  "ruff:E712": {
    "description": "Checks for equality comparisons to boolean literals.",
    "url": "https://docs.astral.sh/ruff/rules/true-false-comparison/"
  },
  "ruff:E713": {
    "description": "Checks for membership tests using not {element} in {collection}.",
    "url": "https://docs.astral.sh/ruff/rules/not-in-test/"
  },
  "ruff:E714": {
    "description": "Checks for identity comparisons using not {foo} is {bar}.",
    "url": "https://docs.astral.sh/ruff/rules/not-is-test/"
  },
  "ruff:E721": {
    "description": "Checks for object type comparisons using == and other comparison operators.",
    "url": "https://docs.astral.sh/ruff/rules/type-comparison/"
  },
  "ruff:E722": {
    "description": "Checks for bare except catches in try-except statements.",
    "url": "https://docs.astral.sh/ruff/rules/bare-except/"
  },
  "ruff:E731": {
    "description": "Checks for lambda expressions which are assigned to a variable.",
    "url": "https://docs.astral.sh/ruff/rules/lambda-assignment/"
  },
  "ruff:E741": {
    "description": "Checks for the use of the characters 'l', 'O', or 'I' as variable names.",
    "url": "https://docs.astral.sh/ruff/rules/ambiguous-variable-name/"
  },
  "ruff:E902": {
    "description": "This is not a regular diagnostic; instead, it's raised when a file cannot be read from disk.",
    "url": "https://docs.astral.sh/ruff/rules/io-error/"
  },
  "ruff:F401": {
    "description": "Checks for unused imports.",
    "url": "https://docs.astral.sh/ruff/rules/unused-import/"
  },
  "ruff:F402": {
    "description": "Checks for import bindings that are shadowed by loop variables.",
    "url": "https://docs.astral.sh/ruff/rules/import-shadowed-by-loop-var/"
  },
  "ruff:F403": {
    "description": "Checks for the use of wildcard imports.",
    "url": "https://docs.astral.sh/ruff/rules/undefined-local-with-import-star/"
  },
  "ruff:F405": {
    "description": "Checks for names that might be undefined, but may also be defined in a wildcard import.",
    "url": "https://docs.astral.sh/ruff/rules/undefined-local-with-import-star-usage/"
  },
  "ruff:F507": {
    "description": "Checks for printf-style format strings that have a mismatch between the number of positional placeholders and the number of substitution values.",
    "url": "https://docs.astral.sh/ruff/rules/percent-format-positional-count-mismatch/"
  },
  "ruff:F521": {
    "description": "Checks for str.format calls with invalid format strings.",
    "url": "https://docs.astral.sh/ruff/rules/string-dot-format-invalid-format/"
  },
  "ruff:F522": {
    "description": "Checks for str.format calls with unused keyword arguments.",
    "url": "https://docs.astral.sh/ruff/rules/string-dot-format-extra-named-arguments/"
  },
  "ruff:F523": {
    "description": "Checks for str.format calls with unused positional arguments.",
    "url": "https://docs.astral.sh/ruff/rules/string-dot-format-extra-positional-arguments/"
  },
  "ruff:F524": {
    "description": "Checks for str.format calls with placeholders that are missing arguments.",
    "url": "https://docs.astral.sh/ruff/rules/string-dot-format-missing-arguments/"
  },
  "ruff:F541": {
    "description": "Checks for f-strings that do not contain any placeholder expressions.",
    "url": "https://docs.astral.sh/ruff/rules/f-string-missing-placeholders/"
  },
  "ruff:F601": {
    "description": "Checks for dictionary literals that associate multiple values with the same key.",
    "url": "https://docs.astral.sh/ruff/rules/multi-value-repeated-key-literal/"
  },
  "ruff:F722": {
    "description": "Checks for forward annotations that include invalid syntax.",
    "url": "https://docs.astral.sh/ruff/rules/forward-annotation-syntax-error/"
  },
  "ruff:F811": {
    "description": "Checks for variable definitions that redefine (or \"shadow\") unused variables.",
    "url": "https://docs.astral.sh/ruff/rules/redefined-while-unused/"
  },
  "ruff:F821": {
    "description": "Checks for uses of undefined names.",
    "url": "https://docs.astral.sh/ruff/rules/undefined-name/"
  },
  "ruff:F823": {
    "description": "Checks for undefined local variables.",
    "url": "https://docs.astral.sh/ruff/rules/undefined-local/"
  },
  "ruff:F841": {
    "description": "Checks for the presence of unused variables in function scopes.",
    "url": "https://docs.astral.sh/ruff/rules/unused-variable/"
  },
  "ruff:F901": {
    "description": "Checks for raise statements that raise NotImplemented.",
    "url": "https://docs.astral.sh/ruff/rules/raise-not-implemented/"
  },
  "ruff:I001": {
    "description": "De-duplicates, groups, and sorts imports based on the provided isort settings.",
    "url": "https://docs.astral.sh/ruff/rules/unsorted-imports/"
  },
  "ruff:N801": {
    "description": "Checks for class names that do not follow the CamelCase convention.",
    "url": "https://docs.astral.sh/ruff/rules/invalid-class-name/"
  },
  "ruff:N802": {
    "description": "Checks for functions names that do not follow the snake_case naming convention.",
    "url": "https://docs.astral.sh/ruff/rules/invalid-function-name/"
  },
  "ruff:N803": {
    "description": "Checks for argument names that do not follow the snake_case convention.",
    "url": "https://docs.astral.sh/ruff/rules/invalid-argument-name/"
  },
  "ruff:N804": {
    "description": "Checks for class methods that use a name other than cls for their first argument.",
    "url": "https://docs.astral.sh/ruff/rules/invalid-first-argument-name-for-class-method/"
  },
  "ruff:N805": {
    "description": "Checks for instance methods that use a name other than self for their first argument.",
    "url": "https://docs.astral.sh/ruff/rules/invalid-first-argument-name-for-method/"
  },
  "ruff:N806": {
    "description": "Checks for the use of non-lowercase variable names in functions.",
    "url": "https://docs.astral.sh/ruff/rules/non-lowercase-variable-in-function/"
  },
  "ruff:N807": {
    "description": "Checks for functions with \"dunder\" names (that is, names with two leading and trailing underscores) that are not documented.",
    "url": "https://docs.astral.sh/ruff/rules/dunder-function-name/"
  },
  "ruff:N812": {
    "description": "Checks for lowercase imports that are aliased to non-lowercase names.",
    "url": "https://docs.astral.sh/ruff/rules/lowercase-imported-as-non-lowercase/"
  },
  "ruff:N813": {
    "description": "Checks for CamelCase imports that are aliased to lowercase names.",
    "url": "https://docs.astral.sh/ruff/rules/camelcase-imported-as-lowercase/"
  },
  "ruff:N816": {
    "description": "Checks for global variable names that follow the mixedCase convention.",
    "url": "https://docs.astral.sh/ruff/rules/mixed-case-variable-in-global-scope/"
  },
  "ruff:N818": {
    "description": "Checks for custom exception definitions that omit the Error suffix.",
    "url": "https://docs.astral.sh/ruff/rules/error-suffix-on-exception-name/"
  },
  "ruff:N999": {
    "description": "Checks for module names that do not follow the snake_case naming convention or are otherwise invalid.",
    "url": "https://docs.astral.sh/ruff/rules/invalid-module-name/"
  },
  "ruff:UP003": {
    "description": "Checks for uses of type that take a primitive as an argument.",
    "url": "https://docs.astral.sh/ruff/rules/type-of-primitive/"
  },
  "ruff:UP004": {
    "description": "Checks for classes that inherit from object.",
    "url": "https://docs.astral.sh/ruff/rules/useless-object-inheritance/"
  },
  "ruff:UP006": {
    "description": "Checks for the use of generics that can be replaced with standard library variants based on [PEP 585].",
    "url": "https://docs.astral.sh/ruff/rules/non-pep585-annotation/"
  },
  "ruff:UP007": {
    "description": "Check for type annotations that can be rewritten based on [PEP 604] syntax.",
    "url": "https://docs.astral.sh/ruff/rules/non-pep604-annotation-union/"
  },
  "ruff:UP008": {
    "description": "Checks for super calls that pass redundant arguments.",
    "url": "https://docs.astral.sh/ruff/rules/super-call-with-parameters/"
  },
  "ruff:UP009": {
    "description": "Checks for unnecessary UTF-8 encoding declarations.",
    "url": "https://docs.astral.sh/ruff/rules/utf8-encoding-declaration/"
  },
  "ruff:UP010": {
    "description": "Checks for unnecessary __future__ imports.",
    "url": "https://docs.astral.sh/ruff/rules/unnecessary-future-import/"
  },
  "ruff:UP011": {
    "description": "Checks for unnecessary parentheses on functools.lru_cache decorators.",
    "url": "https://docs.astral.sh/ruff/rules/lru-cache-without-parameters/"
  },
  "ruff:UP012": {
    "description": "Checks for unnecessary calls to encode as UTF-8.",
    "url": "https://docs.astral.sh/ruff/rules/unnecessary-encode-utf8/"
  },
  "ruff:UP015": {
    "description": "Checks for redundant open mode arguments.",
    "url": "https://docs.astral.sh/ruff/rules/redundant-open-modes/"
  },
  "ruff:UP018": {
    "description": "Checks for unnecessary calls to str, bytes, int, float, bool, and complex.",
    "url": "https://docs.astral.sh/ruff/rules/native-literals/"
  },
  "ruff:UP020": {
    "description": "Checks for uses of io.open.",
    "url": "https://docs.astral.sh/ruff/rules/open-alias/"
  },
  "ruff:UP024": {
    "description": "Checks for uses of exceptions that alias OSError.",
    "url": "https://docs.astral.sh/ruff/rules/os-error-alias/"
  },
  "ruff:UP025": {
    "description": "Checks for uses of the Unicode kind prefix (u) in strings.",
    "url": "https://docs.astral.sh/ruff/rules/unicode-kind-prefix/"
  },
  "ruff:UP028": {
    "description": "Checks for for loops that can be replaced with yield from expressions.",
    "url": "https://docs.astral.sh/ruff/rules/yield-in-for-loop/"
  },
  "ruff:UP029": {
    "description": "Checks for imports of Python 3 builtins from Python 2 compatibility shims such as python-future and six.",
    "url": "https://docs.astral.sh/ruff/rules/unnecessary-builtin-import/"
  },
  "ruff:UP030": {
    "description": "Checks for unnecessary positional indices in format strings.",
    "url": "https://docs.astral.sh/ruff/rules/format-literals/"
  },
  "ruff:UP031": {
    "description": "Checks for printf-style string formatting, and offers to replace it with str.format calls.",
    "url": "https://docs.astral.sh/ruff/rules/printf-string-formatting/"
  },
  "ruff:UP032": {
    "description": "Checks for str.format calls that can be replaced with f-strings.",
    "url": "https://docs.astral.sh/ruff/rules/f-string/"
  },
  "ruff:UP034": {
    "description": "Checks for extraneous parentheses.",
    "url": "https://docs.astral.sh/ruff/rules/extraneous-parentheses/"
  },
  "ruff:UP035": {
    "description": "Checks for uses of deprecated imports based on the minimum supported Python version.",
    "url": "https://docs.astral.sh/ruff/rules/deprecated-import/"
  },
  "ruff:UP036": {
    "description": "Checks for conditional blocks gated on sys.version_info comparisons that are outdated for the minimum supported Python version.",
    "url": "https://docs.astral.sh/ruff/rules/outdated-version-block/"
  },
  "ruff:UP037": {
    "description": "Checks for the presence of unnecessary quotes in type annotations.",
    "url": "https://docs.astral.sh/ruff/rules/quoted-annotation/"
  },
  "ruff:UP039": {
    "description": "Checks for class definitions that include unnecessary parentheses after the class name.",
    "url": "https://docs.astral.sh/ruff/rules/unnecessary-class-parentheses/"
  },
  "ruff:UP040": {
    "description": "Checks for use of TypeAlias annotations and TypeAliasType assignments for declaring type aliases.",
    "url": "https://docs.astral.sh/ruff/rules/non-pep695-type-alias/"
  },
  "ruff:UP045": {
    "description": "Check for typing.Optional annotations that can be rewritten based on [PEP 604] syntax.",
    "url": "https://docs.astral.sh/ruff/rules/non-pep604-annotation-optional/"
  },
  "ruff:UP046": {
    "description": "Checks for use of standalone type variables and parameter specifications in generic classes.",
    "url": "https://docs.astral.sh/ruff/rules/non-pep695-generic-class/"
  },
  "ruff:UP047": {
    "description": "Checks for use of standalone type variables and parameter specifications in generic functions.",
    "url": "https://docs.astral.sh/ruff/rules/non-pep695-generic-function/"
  },
  "ruff:invalid-syntax": {
    "description": "The file could not be parsed as valid Python syntax, so Ruff could not complete normal rule analysis for it.",
    "url": "https://docs.astral.sh/ruff/linter/"
  }
}
